### ISSUE TITLE
Add rebrandly link to GitHub

### ISSUE THREAD

**Issue by lcolladotor** [Bioconductor/BiocWorkshops2019#37]
Hi,

I think that it'll be useful to add https://rebrand.ly/biocworkshops2019 to GItHub. My understanding is that this link will work in the future whenever http://biocworkshops2019.bioconductor.org.s3-website-us-east-1.amazonaws.com/ changes or something like that.

Also, I couldn't find this link on the BioC2019 website earlier today when I was trying to point someone to the rendered workshops.

Best,
Leo

**Comment by LiNk-NY** [comment]
Thanks Leo, I've added the link to the `README.md`
